<?php

$countries = array(
  array('country_id' => 'AC','name' => 'Остров Вознесения'),
  array('country_id' => 'AD','name' => 'Андорра'),
  array('country_id' => 'AE','name' => 'ОАЭ'),
  array('country_id' => 'AF','name' => 'Афганистан'),
  array('country_id' => 'AG','name' => 'Антигуа и Барбуда'),
  array('country_id' => 'AI','name' => 'Ангилья'),
  array('country_id' => 'AL','name' => 'Албания'),
  array('country_id' => 'AM','name' => 'Армения'),
  array('country_id' => 'AN','name' => 'Нидерландские Антильские о-ва'),
  array('country_id' => 'AO','name' => 'Ангола'),
  array('country_id' => 'AQ','name' => 'Антарктида'),
  array('country_id' => 'AR','name' => 'Аргентина'),
  array('country_id' => 'AS','name' => 'Американское Самоа'),
  array('country_id' => 'AT','name' => 'Австрия'),
  array('country_id' => 'AU','name' => 'Австралия'),
  array('country_id' => 'AW','name' => 'Аруба'),
  array('country_id' => 'AX','name' => 'Аландские о-ва'),
  array('country_id' => 'AZ','name' => 'Азербайджан'),
  array('country_id' => 'BA','name' => 'Босния и Герцеговина'),
  array('country_id' => 'BB','name' => 'Барбадос'),
  array('country_id' => 'BD','name' => 'Бангладеш'),
  array('country_id' => 'BE','name' => 'Бельгия'),
  array('country_id' => 'BF','name' => 'Буркина Фасо'),
  array('country_id' => 'BG','name' => 'Болгария'),
  array('country_id' => 'BH','name' => 'Бахрейн'),
  array('country_id' => 'BI','name' => 'Бурунди'),
  array('country_id' => 'BJ','name' => 'Бенин'),
  array('country_id' => 'BL','name' => 'Остров Святого Бартоломея'),
  array('country_id' => 'BM','name' => 'Бермудские о-ва'),
  array('country_id' => 'BN','name' => 'Бруней Даруссалам'),
  array('country_id' => 'BO','name' => 'Боливия'),
  array('country_id' => 'BR','name' => 'Бразилия'),
  array('country_id' => 'BS','name' => 'Багамские о-ва'),
  array('country_id' => 'BT','name' => 'Бутан'),
  array('country_id' => 'BV','name' => 'Остров Буве'),
  array('country_id' => 'BW','name' => 'Ботсвана'),
  array('country_id' => 'BY','name' => 'Беларусь'),
  array('country_id' => 'BZ','name' => 'Белиз'),
  array('country_id' => 'CA','name' => 'Канада'),
  array('country_id' => 'CC','name' => 'Кокосовые о-ва'),
  array('country_id' => 'CD','name' => 'Демократическая Республика Конго'),
  array('country_id' => 'CF','name' => 'ЦАР'),
  array('country_id' => 'CG','name' => 'Конго'),
  array('country_id' => 'CH','name' => 'Швейцария'),
  array('country_id' => 'CI','name' => 'Кот д’Ивуар'),
  array('country_id' => 'CK','name' => 'Острова Кука'),
  array('country_id' => 'CL','name' => 'Чили'),
  array('country_id' => 'CM','name' => 'Камерун'),
  array('country_id' => 'CN','name' => 'Китай'),
  array('country_id' => 'CO','name' => 'Колумбия'),
  array('country_id' => 'CP','name' => 'Остров Клиппертон'),
  array('country_id' => 'CR','name' => 'Коста-Рика'),
  array('country_id' => 'CS','name' => 'Сербия и Черногория'),
  array('country_id' => 'CU','name' => 'Куба'),
  array('country_id' => 'CV','name' => 'Острова Зеленого Мыса'),
  array('country_id' => 'CX','name' => 'Остров Рождества'),
  array('country_id' => 'CY','name' => 'Кипр'),
  array('country_id' => 'CZ','name' => 'Чехия'),
  array('country_id' => 'DE','name' => 'Германия'),
  array('country_id' => 'DG','name' => 'Диего-Гарсия'),
  array('country_id' => 'DJ','name' => 'Джибути'),
  array('country_id' => 'DK','name' => 'Дания'),
  array('country_id' => 'DM','name' => 'Доминика'),
  array('country_id' => 'DO','name' => 'Доминиканская Республика'),
  array('country_id' => 'DZ','name' => 'Алжир'),
  array('country_id' => 'EA','name' => 'Сеута и Мелилья'),
  array('country_id' => 'EC','name' => 'Эквадор'),
  array('country_id' => 'EE','name' => 'Эстония'),
  array('country_id' => 'EG','name' => 'Египет'),
  array('country_id' => 'EH','name' => 'Западная Сахара'),
  array('country_id' => 'ER','name' => 'Эритрея'),
  array('country_id' => 'ES','name' => 'Испания'),
  array('country_id' => 'ET','name' => 'Эфиопия'),
  array('country_id' => 'EU','name' => 'Европейский союз'),
  array('country_id' => 'FI','name' => 'Финляндия'),
  array('country_id' => 'FJ','name' => 'Фиджи'),
  array('country_id' => 'FK','name' => 'Фолклендские о-ва'),
  array('country_id' => 'FM','name' => 'Федеративные Штаты Микронезии'),
  array('country_id' => 'FO','name' => 'Фарерские о-ва'),
  array('country_id' => 'FR','name' => 'Франция'),
  array('country_id' => 'GA','name' => 'Габон'),
  array('country_id' => 'GB','name' => 'Великобритания'),
  array('country_id' => 'GD','name' => 'Гренада'),
  array('country_id' => 'GE','name' => 'Грузия'),
  array('country_id' => 'GF','name' => 'Французская Гвиана'),
  array('country_id' => 'GG','name' => 'Гернси'),
  array('country_id' => 'GH','name' => 'Гана'),
  array('country_id' => 'GI','name' => 'Гибралтар'),
  array('country_id' => 'GL','name' => 'Гренландия'),
  array('country_id' => 'GM','name' => 'Гамбия'),
  array('country_id' => 'GN','name' => 'Гвинея'),
  array('country_id' => 'GP','name' => 'Гваделупа'),
  array('country_id' => 'GQ','name' => 'Экваториальная Гвинея'),
  array('country_id' => 'GR','name' => 'Греция'),
  array('country_id' => 'GS','name' => 'Южная Джорджия и Южные Сандвичевы Острова'),
  array('country_id' => 'GT','name' => 'Гватемала'),
  array('country_id' => 'GU','name' => 'Гуам'),
  array('country_id' => 'GW','name' => 'Гвинея-Бисау'),
  array('country_id' => 'GY','name' => 'Гайана'),
  array('country_id' => 'HK','name' => 'Гонконг (особый район)'),
  array('country_id' => 'HM','name' => 'Острова Херд и Макдональд'),
  array('country_id' => 'HN','name' => 'Гондурас'),
  array('country_id' => 'HR','name' => 'Хорватия'),
  array('country_id' => 'HT','name' => 'Гаити'),
  array('country_id' => 'HU','name' => 'Венгрия'),
  array('country_id' => 'IC','name' => 'Канарские о-ва'),
  array('country_id' => 'ID','name' => 'Индонезия'),
  array('country_id' => 'IE','name' => 'Ирландия'),
  array('country_id' => 'IL','name' => 'Израиль'),
  array('country_id' => 'IM','name' => 'Остров Мэн'),
  array('country_id' => 'IN','name' => 'Индия'),
  array('country_id' => 'IO','name' => 'Британская территория в Индийском океане'),
  array('country_id' => 'IQ','name' => 'Ирак'),
  array('country_id' => 'IR','name' => 'Иран'),
  array('country_id' => 'IS','name' => 'Исландия'),
  array('country_id' => 'IT','name' => 'Италия'),
  array('country_id' => 'JE','name' => 'Джерси'),
  array('country_id' => 'JM','name' => 'Ямайка'),
  array('country_id' => 'JO','name' => 'Иордания'),
  array('country_id' => 'JP','name' => 'Япония'),
  array('country_id' => 'KE','name' => 'Кения'),
  array('country_id' => 'KG','name' => 'Киргизия'),
  array('country_id' => 'KH','name' => 'Камбоджа'),
  array('country_id' => 'KI','name' => 'Кирибати'),
  array('country_id' => 'KM','name' => 'Коморские о-ва'),
  array('country_id' => 'KN','name' => 'Сент-Киттс и Невис'),
  array('country_id' => 'KP','name' => 'Северная Корея'),
  array('country_id' => 'KR','name' => 'Республика Корея'),
  array('country_id' => 'KW','name' => 'Кувейт'),
  array('country_id' => 'KY','name' => 'Каймановы острова'),
  array('country_id' => 'KZ','name' => 'Казахстан'),
  array('country_id' => 'LA','name' => 'Лаос'),
  array('country_id' => 'LB','name' => 'Ливан'),
  array('country_id' => 'LC','name' => 'Сент-Люсия'),
  array('country_id' => 'LI','name' => 'Лихтенштейн'),
  array('country_id' => 'LK','name' => 'Шри-Ланка'),
  array('country_id' => 'LR','name' => 'Либерия'),
  array('country_id' => 'LS','name' => 'Лесото'),
  array('country_id' => 'LT','name' => 'Литва'),
  array('country_id' => 'LU','name' => 'Люксембург'),
  array('country_id' => 'LV','name' => 'Латвия'),
  array('country_id' => 'LY','name' => 'Ливия'),
  array('country_id' => 'MA','name' => 'Марокко'),
  array('country_id' => 'MC','name' => 'Монако'),
  array('country_id' => 'MD','name' => 'Молдова'),
  array('country_id' => 'ME','name' => 'Черногория'),
  array('country_id' => 'MF','name' => 'Остров Святого Мартина'),
  array('country_id' => 'MG','name' => 'Мадагаскар'),
  array('country_id' => 'MH','name' => 'Маршалловы о-ва'),
  array('country_id' => 'MK','name' => 'Македония'),
  array('country_id' => 'ML','name' => 'Мали'),
  array('country_id' => 'MM','name' => 'Мьянма'),
  array('country_id' => 'MN','name' => 'Монголия'),
  array('country_id' => 'MO','name' => 'Макао (особый район)'),
  array('country_id' => 'MP','name' => 'Северные Марианские о-ва'),
  array('country_id' => 'MQ','name' => 'Мартиника'),
  array('country_id' => 'MR','name' => 'Мавритания'),
  array('country_id' => 'MS','name' => 'Монтсеррат'),
  array('country_id' => 'MT','name' => 'Мальта'),
  array('country_id' => 'MU','name' => 'Маврикий'),
  array('country_id' => 'MV','name' => 'Мальдивские о-ва'),
  array('country_id' => 'MW','name' => 'Малави'),
  array('country_id' => 'MX','name' => 'Мексика'),
  array('country_id' => 'MY','name' => 'Малайзия'),
  array('country_id' => 'MZ','name' => 'Мозамбик'),
  array('country_id' => 'NA','name' => 'Намибия'),
  array('country_id' => 'NC','name' => 'Новая Каледония'),
  array('country_id' => 'NE','name' => 'Нигер'),
  array('country_id' => 'NF','name' => 'Остров Норфолк'),
  array('country_id' => 'NG','name' => 'Нигерия'),
  array('country_id' => 'NI','name' => 'Никарагуа'),
  array('country_id' => 'NL','name' => 'Нидерланды'),
  array('country_id' => 'NO','name' => 'Норвегия'),
  array('country_id' => 'NP','name' => 'Непал'),
  array('country_id' => 'NR','name' => 'Науру'),
  array('country_id' => 'NU','name' => 'Ниуе'),
  array('country_id' => 'NZ','name' => 'Новая Зеландия'),
  array('country_id' => 'OM','name' => 'Оман'),
  array('country_id' => 'PA','name' => 'Панама'),
  array('country_id' => 'PE','name' => 'Перу'),
  array('country_id' => 'PF','name' => 'Французская Полинезия'),
  array('country_id' => 'PG','name' => 'Папуа – Новая Гвинея'),
  array('country_id' => 'PH','name' => 'Филиппины'),
  array('country_id' => 'PK','name' => 'Пакистан'),
  array('country_id' => 'PL','name' => 'Польша'),
  array('country_id' => 'PM','name' => 'Сен-Пьер и Микелон'),
  array('country_id' => 'PN','name' => 'Питкэрн'),
  array('country_id' => 'PR','name' => 'Пуэрто-Рико'),
  array('country_id' => 'PS','name' => 'Палестинские территории'),
  array('country_id' => 'PT','name' => 'Португалия'),
  array('country_id' => 'PW','name' => 'Палау'),
  array('country_id' => 'PY','name' => 'Парагвай'),
  array('country_id' => 'QA','name' => 'Катар'),
  array('country_id' => 'QO','name' => 'Внешняя Океания'),
  array('country_id' => 'RE','name' => 'Реюньон'),
  array('country_id' => 'RO','name' => 'Румыния'),
  array('country_id' => 'RS','name' => 'Сербия'),
  array('country_id' => 'RU','name' => 'Россия'),
  array('country_id' => 'RW','name' => 'Руанда'),
  array('country_id' => 'SA','name' => 'Саудовская Аравия'),
  array('country_id' => 'SB','name' => 'Соломоновы о-ва'),
  array('country_id' => 'SC','name' => 'Сейшельские о-ва'),
  array('country_id' => 'SD','name' => 'Судан'),
  array('country_id' => 'SE','name' => 'Швеция'),
  array('country_id' => 'SG','name' => 'Сингапур'),
  array('country_id' => 'SH','name' => 'Остров Святой Елены'),
  array('country_id' => 'SI','name' => 'Словения'),
  array('country_id' => 'SJ','name' => 'Свальбард и Ян-Майен'),
  array('country_id' => 'SK','name' => 'Словакия'),
  array('country_id' => 'SL','name' => 'Сьерра-Леоне'),
  array('country_id' => 'SM','name' => 'Сан-Марино'),
  array('country_id' => 'SN','name' => 'Сенегал'),
  array('country_id' => 'SO','name' => 'Сомали'),
  array('country_id' => 'SR','name' => 'Суринам'),
  array('country_id' => 'ST','name' => 'Сан-Томе и Принсипи'),
  array('country_id' => 'SV','name' => 'Сальвадор'),
  array('country_id' => 'SY','name' => 'Сирия'),
  array('country_id' => 'SZ','name' => 'Свазиленд'),
  array('country_id' => 'TA','name' => 'Тристан-да-Кунья'),
  array('country_id' => 'TC','name' => 'Острова Тёркс и Кайкос'),
  array('country_id' => 'TD','name' => 'Чад'),
  array('country_id' => 'TF','name' => 'Французские Южные Территории'),
  array('country_id' => 'TG','name' => 'Того'),
  array('country_id' => 'TH','name' => 'Таиланд'),
  array('country_id' => 'TJ','name' => 'Таджикистан'),
  array('country_id' => 'TK','name' => 'Токелау'),
  array('country_id' => 'TL','name' => 'Восточный Тимор'),
  array('country_id' => 'TM','name' => 'Туркменистан'),
  array('country_id' => 'TN','name' => 'Тунис'),
  array('country_id' => 'TO','name' => 'Тонга'),
  array('country_id' => 'TR','name' => 'Турция'),
  array('country_id' => 'TT','name' => 'Тринидад и Тобаго'),
  array('country_id' => 'TV','name' => 'Тувалу'),
  array('country_id' => 'TW','name' => 'Тайвань'),
  array('country_id' => 'TZ','name' => 'Танзания'),
  array('country_id' => 'UA','name' => 'Украина'),
  array('country_id' => 'UG','name' => 'Уганда'),
  array('country_id' => 'UM','name' => 'Внешние малые острова (США)'),
  array('country_id' => 'US','name' => 'США'),
  array('country_id' => 'UY','name' => 'Уругвай'),
  array('country_id' => 'UZ','name' => 'Узбекистан'),
  array('country_id' => 'VA','name' => 'Ватикан'),
  array('country_id' => 'VC','name' => 'Сент-Винсент и Гренадины'),
  array('country_id' => 'VE','name' => 'Венесуэла'),
  array('country_id' => 'VG','name' => 'Британские Виргинские о-ва'),
  array('country_id' => 'VI','name' => 'Виргинские о-ва (США)'),
  array('country_id' => 'VN','name' => 'Вьетнам'),
  array('country_id' => 'VU','name' => 'Вануату'),
  array('country_id' => 'WF','name' => 'Уоллис и Футуна'),
  array('country_id' => 'WS','name' => 'Самоа'),
  array('country_id' => 'YE','name' => 'Йемен'),
  array('country_id' => 'YT','name' => 'Майотта'),
  array('country_id' => 'ZA','name' => 'ЮАР'),
  array('country_id' => 'ZM','name' => 'Замбия'),
  array('country_id' => 'ZW','name' => 'Зимбабве')
);
